;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
           dabbrev-expand
           electric-pair-delete-pair
           evil-append
           evil-backward-word-begin
           evil-beginning-of-line
           evil-delete
           evil-delete-backward-char-and-join
           evil-end-of-line
           evil-force-normal-state
           evil-forward-char
           evil-forward-word-begin
           evil-forward-word-end
           evil-goto-first-line
           evil-insert
           evil-next-line
           evil-next-line-1-first-non-blank
           evil-normal-state
           evil-previous-line
           evil-undo
           keyboard-escape-quit
           mouse-set-region
           wdired-exit
           wdired-next-line
           wdired-previous-line
           ))

(setq mc/cmds-to-run-once
      '(
           wdired--self-insert
           ))
